EGSW.Web/Controllers/AjaxController.cs
using EGSW.Data;
using EGSW.Services;
using EGSW.Services.Directory;
using EGSW.Services.ServiceRequests;
using EGSW.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EGSW.Web.Controllers
{
    public class AjaxController : Controller
    {

        private readonly IZipCodeService _zipCodeService;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly IServiceRequestService _serviceRequestService;

        public AjaxController(IZipCodeService zipCodeService, IWorkflowMessageService workflowMessageService
            , IServiceRequestService serviceRequestService)
        {
            this._zipCodeService = zipCodeService;
            this._workflowMessageService = workflowMessageService;
            this._serviceRequestService = serviceRequestService;

        }

        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetSongs(string searchTerm)
        {
            List<Songs> songList = new List<Songs>();
            songList.Add(new Songs { Name = "Addat", Artist = "Aatif Aslam" });
            songList.Add(new Songs { Name = "Woh Lamhey", Artist = "Jal - The band" });
            songList.Add(new Songs { Name = "Kryptonite", Artist = "3 Doors Down" });
            songList.Add(new Songs { Name = "Manja", Artist = "Amit Trivedi" });
            songList.Add(new Songs { Name = "Tum hi ho", Artist = "Arjit Singh" });

            //songList = songList.Where(m => m.Name.Contains(searchTerm)).ToList();

            //return songList;
            return Json(songList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCityStateInfoBasedOnZipcode(string inputzipcode)
        {
            var zipcodeResult = _zipCodeService.GetZipCodeDetailByZipcode(inputzipcode);
            //return songList;
            return Json(zipcodeResult, JsonRequestBehavior.AllowGet);
        }


        public JsonResult ValidateZipcode(string inputzipcode,string messageElementId)
        {
            bool Result = false;
            string message = string.Empty;
            string City = string.Empty;
            string State = string.Empty;
            string StateAbb = string.Empty;
            var zipcodeResult = _zipCodeService.GetZipCodeDetailByZipcode(inputzipcode);

            if (zipcodeResult != null)
            {
                Result = true;
                City = zipcodeResult.CityName;
                State = zipcodeResult.StateName;
                StateAbb = zipcodeResult.StateAbbr;
                message = City + ", " + State;
            }
            else
            {
                message = "Zipcode is not valid.";
            }

            return Json(new { Result = Result, message = message, messageElementId = messageElementId, City = City, State = State, StateAbb = StateAbb }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult SendNewServiewRequest(NewServiceRequestModel model)
        {

            if (ModelState.IsValid)
            {
                ServiceRequest entity = new ServiceRequest();
                entity.CreatedOnUtc = DateTime.UtcNow;
                entity.EmailAddress = model.ServiceEmailAdddress;
                entity.Zipcode = model.ServiceZipCode;

                _serviceRequestService.InsertServiceRequest(entity);

                //_workflowMessageService.SendNewServiceRequestSiteOwnerNotification(model.ServiceEmailAdddress, model.ServiceZipCode);
                model.Result = true;

            }
            else
            {
                model.Result = false;
                model.Message = "Somthing Wrong.";
            }


            //return songList;
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }

    public class Songs
    {
        public string Name { get; set; }        
        public string Artist { get; set; }
    }
}

EGSW.Web/Controllers/CommonController.cs
using EGSW.Data;
using EGSW.Data.Customers;
using EGSW.Framework;
using EGSW.Services;
using EGSW.Services.Authentication;
using EGSW.Web.ActionFilters;
using EGSW.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.IO;

namespace EGSW.Web.Controllers
{
    [RequreSecureConnectionFilter]
    public class CommonController : Controller
    {

         private readonly IAuthenticationService _authenticationService;  
        private readonly ICustomerService _customerService;
        private readonly IWorkContext _workContext;
        private readonly IWorkflowMessageService _workflowMessageService;

        public CommonController(ICustomerService customerService, IWorkContext workContext, 
            IAuthenticationService authenticationService,
            IWorkflowMessageService workflowMessageService)
        {
            this._customerService = customerService;
            this._workContext = workContext;
            this._authenticationService = authenticationService;
            this._workflowMessageService = workflowMessageService;

        }

        public ActionResult Index(int Id)
        {
            //get here from Database;
            var _seoUrlService = DependencyResolver.Current.GetService<EGSW.Services.SeoUrls.ISeoUrlService>();
            var Result = _seoUrlService.GetSeoUrlById(Id);
            
            var randomList = _seoUrlService.GetCountySeoUrl(Result.CountyName).OrderBy(n => Guid.NewGuid()).Take(5);
            //var randomList = _seoUrlService.GetAllSeoUrl().OrderBy(n => Guid.NewGuid()).Take(5);
            ViewBag.SeoRandomList = randomList;

            return View(Result);
        }

        public ActionResult Update()
        {
            var _seoUrlService = DependencyResolver.Current.GetService<EGSW.Services.SeoUrls.ISeoUrlService>();

            var seoUrlList = _seoUrlService.GetAllSeoUrl();
            seoUrlList = seoUrlList.Where(i => i.Id > 66).ToList();
            foreach (SeoUrl entity in seoUrlList)
            {
                entity.SeoName = entity.CityName.Replace(" ", "-") + "-" + entity.CountyName.Replace("-county", "") + "-" + entity.StateAbbr.Replace(" ", "-");
                entity.SeoName = entity.SeoName.ToLower();
                _seoUrlService.UpdateSeoUrl(entity);

            }

            return Content("All Url Update");
        }


        public ActionResult SeoSitemapXml()
        {
            List<ISitemapItem> _items;
            _items = new List<ISitemapItem>();


            string siteUrl = ConfigurationManager.AppSettings["SiteUrl"];
            siteUrl = siteUrl.Remove(siteUrl.LastIndexOf("/"));
            //_items.Add(new SitemapItem(siteUrl+Url.RouteUrl("HomePage")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("AboutUs")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("ContactUs")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("FAQ")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("ReferANeighbor")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("Register")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("Login")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
            //_items.Add(new SitemapItem(siteUrl + Url.RouteUrl("PasswordRecovery")) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });

            string line;
            string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content\\URL.txt");

            try
            {
                System.IO.StreamReader file = new System.IO.StreamReader(path);
                //_items.Add(new SitemapItem(siteUrl) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
                while ((line = file.ReadLine()) != null)
                {
                    _items.Add(new SitemapItem(siteUrl + Url.RouteUrl(line)) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });
                }

                file.Close();
            }
            catch (Exception e) { }

            
            
            var _seoUrlService = DependencyResolver.Current.GetService<EGSW.Services.SeoUrls.ISeoUrlService>();

            var seoUrlList = _seoUrlService.GetAllSeoUrl();

            
            foreach (var entity in seoUrlList)
            {

                _items.Add(new SitemapItem(ConfigurationManager.AppSettings["SiteUrl"] +entity.SeoName) { ChangeFrequency = ChangeFrequency.Monthly, LastModified = DateTime.Now, Priority = 1 });

            }

            




            return new XmlSitemapResult(_items);
        }


        //header links
        [ChildActionOnly]
        public ActionResult HeaderLinks()
        {
            var customer = _workContext.CurrentCustomer;



            var model = new HeaderLinksModel
            {
                IsAuthenticated = (customer.IsRegistered() || customer.IsAdmin() || customer.IsAgent())?true:false,
                CustomerEmailUsername = (customer.IsRegistered() || customer.IsAdmin() || customer.IsAgent()) ? customer.Email : "",
                DisplayAdminLink = (customer.IsAdmin() || customer.IsAgent()),

            };

            if (customer.IsAdmin())
            {
                model.Text = "Admin";
            }
            else if (customer.IsAgent())
            {
                model.Text = "Agent";
            }

            //var model = new HeaderLinksModel
            //{
            //    IsAuthenticated = customer.IsRegistered(),
            //    CustomerEmailUsername = customer.IsRegistered() ? customer.Email : "",
            //    DisplayAdminLink = customer.IsAdmin(),

            //};

           
            
            return PartialView(model);
        }

        public ActionResult CityNames()
        {
            var val = Request.QueryString["name"];
            //get here from Database;
            var city = val;
            var _seoUrlService = DependencyResolver.Current.GetService<EGSW.Services.SeoUrls.ISeoUrlService>();
           // var Result = _seoUrlService.GetCountySeoUrl(city);

            var randomList = _seoUrlService.GetCountySeoUrl(city).OrderBy(n => n.CityName);
            ViewBag.SeoRandomList = randomList;
            ViewBag.countyName = city;
            return View();
            //return View();
        }
        
        public ActionResult ReferANeighbor()
        {
            ReferNeighborModel model = new ReferNeighborModel();

            return View(model);
        }

        [HttpPost]
        [CaptchaValidator]
        public ActionResult ReferANeighbor(ReferNeighborModel model, bool captchaValid)
        {
            if (!captchaValid)
            {
                ModelState.AddModelError("", "Wrong Captcha code.");
            }

            if (ModelState.IsValid)
            {
                model.Result = true;



                _workflowMessageService.SendReferANeighborMessage(model.FriendName, model.FriendEmail, model.YourName);
            }

            return View(model);
        }
        
    }
}

EGSW.Web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Page Not Found";
}

<h1>Page Not Found</h1>
<p>Could not find the page: @ViewBag.RequestedUrl</p>
@if (ViewBag.ReferrerUrl != null) {
<p>Go back to the <a href="@ViewBag.ReferrerUrl">previous page</a>.</p>
}

@* Error page must be longer than 512 bytes for IE and Chrome to show it. 
   So add padding in case we're short. *@
@(new string(' ', 512))

EGSW.Web/Views/Shared/_AdminLayout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin EGSW</title>
    @Styles.Render("~/adminContent/css")
        @Scripts.Render("~/adminbundles/modernizr")
        <script src="~/Scripts/jquery-1.10.2.js"></script>
    
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EGSW", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.RouteLink("About", "CommingSoon")</li>
                    <li>@Html.RouteLink("Contact", "ContactUs")</li>
                    <li>@Html.RouteLink("FAQ", "CommingSoon")</li>
                    @*<li>@Html.ActionLink("Gutter Clean Request", "GutterCleanRequest", "Home")</li>*@
                </ul>
                @*@Html.Partial("_LoginPartial")*@                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
    </div>
    
    <div class="clearfix" style="margin:0 0 20px;"></div>
    <div class="footer">
        <div class="footer_midle">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <ul class="social_left">
                            <li class="facebook"><a href="#"><i class="fa fa-facebook-square fa-3x"></i></a></li>
                            <li class="fb_text">
                                <h4><a href="#">Follow us on Facebook</a></h4>
                            </li>
                            <div class="clearfix"> </div>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="social_left">
                            <li class="facebook"><a href="#"><i class="fa fa-twitter-square fa-3x"></i></a></li>
                            <li class="fb_text">
                                <h4><a href="#">Follow us on Twitter</a></h4>
                            </li>
                            <div class="clearfix"> </div>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="social_left">
                            <li class="facebook"><a href="#"><i class="fa fa-google-plus-square fa-3x"></i></a></li>
                            <li class="fb_text">
                                <h4><a href="#">Follow us on Google +</a></h4>
                            </li>
                            <div class="clearfix"> </div>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="social_left">
                            <li class="facebook"><a href="#"><i class="fa fa-linkedin-square fa-3x"></i></a></li>
                            <li class="fb_text">
                                <h4><a href="#">Follow us on LinkedIn</a></h4>
                            </li>
                            <div class="clearfix"> </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">

            <div class="footer-lower">
               
                    <div class="footer-info">
                        <span class="footer-disclaimer">Copyright &copy; @DateTime.Now.Year All rights reserved.</span>
                    </div>
                    <div class="footer-powered-by">
                        Powered by <a href="http://circustechnologies.com/">Circus Technologies</a>

                    </div>

               
            </div>

</div>
        </div>
        

    @Scripts.Render("~/adminbundles/jquery")
    @Scripts.Render("~/adminbundles/bootstrap")
    @RenderSection("scripts", required: false)


    @section Scripts {
        @Scripts.Render("~/adminbundles/jqueryval")
    }




</body>
</html>

EGSW.Web/Views/Shared/_AjaxGridPager.cshtml
@model GridMvc.Site.Models.Grids.AjaxGridPager
@if (!Model.HasPages)
{
    return;
}
<div class="grid-ajax-pager">
    <a href="javascript:void(0);">Show more</a>
</div>

<script>
    (function ($) {
        var self = this;
        this.currentPage = 1;

        var pageLink = $(".grid-ajax-pager a");
        var gridTableBody = pageLink.closest(".grid-wrap").find("tbody");

        pageLink.on("click", function () {
            self.loadNextPage();
        });

        this.loadNextPage = function () {
            self.currentPage++;

            $.get("/Home/GetOrdersGridRows" + self.pad(location.search) + self.currentPage)
                .done(function (response) {

                    gridTableBody.append(response.Html);
                    if (!response.HasItems)
                        pageLink.hide();
                })
                .fail(function () {
                    alert("cannot load items");
                });
        };

        this.pad = function (query) {
            if (query.length == 0) return "?page=";
            return query + "&page=";
        };
    })(jQuery);
</script>

EGSW.Web/Views/Shared/_ColumnsOne.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="master-wrapper-content">
    @RenderBody()
</div>

EGSW.Web/Views/Shared/_ColumnsTwo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-3">
    @if (IsSectionDefined("left"))
    {
        @RenderSection("left")
    }
    else
    {
        <text></text>
    }
</div>
<div class="col-md-9">

    @RenderBody()

</div>

EGSW.Web/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

EGSW.Web/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

EGSW.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>

    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {

            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),

        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)

    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');



    ga('create', 'UA-67045220-3', 'auto');

    ga('send', 'pageview');




    </script>
    <title>@ViewBag.Title</title>
    @if (ViewBag.MetaDescription!=null)
    { 
        <meta name="Description" content="@ViewBag.MetaDescription" />
    }


    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <script src="~/Scripts/jquery-1.10.2.js"></script>
    
    <link href="~/Content/font-awesome.css" rel="stylesheet" />

    <script src="~/Scripts/public.zipcode.js?v=1.5"></script>
    <script type="text/javascript">
        ZipCodeMethod.init("request-method-message", '@Url.Action("ValidateZipcode", "Ajax")');
    </script>
      
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.RouteUrl("HomePage")" class="navbar-brand" style="position:absolute;z-index:999;padding:0px;">

                    <img src="~/images/logo.jpg"/>

                 </a>

                @*@Html.ActionLink("ericsguttercleaning.com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">                  
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.RouteLink("About", "AboutUs")</li>
                    <li>@Html.RouteLink("Contact", "ContactUs")</li>
                    <li>@Html.RouteLink("FAQ", "FAQ")</li>
                    <li>@Html.RouteLink("Refer A Neighbor", "ReferANeighbor")</li>                    
                </ul>                
                @Html.Action("HeaderLinks", "Common")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
    </div>
    
    <div class="clearfix" style="margin:0 0 20px;"></div>
    <div class="footer">
        <div class="footer_midle">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Historical:</h4>
                        <p class="text-justify">
                            Eric's Gutter Cleaning  was started by a very successful gutter, roofing and drainage company owner after 18 prosperous years in the gutter construction business.   Being an efficiency and systems purist, he couldn't accept the reality that his company was successfully charging almost 220% more than what he thought it would cost to clean gutters.  He realized that in order to lower price, a paradigm shift must occur.
                        </p>
                        <p class="text-justify">
                            By eliminating logistical challenges, customer service inefficiencies, billing inefficiencies and new customers evident apprehension of being "upsold" or sold into buying unsolicited services, he could provide better gutter cleaning service at about 55% reduction in cost.
                        </p>
                        <p class="text-justify">
                            With the help of a technical co-founder, Eric's Gutter Cleaning  was born.
                        </p>
                        <p class="text-justify">
                            Most of what you will order with exception to customer service, all the mechanics of your transaction will be automated.  We will thereby be freed up to focus on one thing: cleaning your gutters well, fast and consequently, inexpensively.
                        </p>
                        <p class="text-justify">
                            We’re the good guys, we hope you will agree.

                        </p>
                        </div>
                    </div>
                </div>
                    @*<div class="container">
                        <div class="row">
                            <div class="col-md-3">
                                <ul class="social_left">
                                    <li class="facebook"><a href="#"><i class="fa fa-facebook-square fa-3x"></i></a></li>
                                    <li class="fb_text">
                                        <h4><a href="#">Follow us on Facebook</a></h4>
                                    </li>
                                    <div class="clearfix"> </div>
                                </ul>
                            </div>
                            <div class="col-md-3">
                                <ul class="social_left">
                                    <li class="facebook"><a href="#"><i class="fa fa-twitter-square fa-3x"></i></a></li>
                                    <li class="fb_text">
                                        <h4><a href="#">Follow us on Twitter</a></h4>
                                    </li>
                                    <div class="clearfix"> </div>
                                </ul>
                            </div>
                            <div class="col-md-3">
                                <ul class="social_left">
                                    <li class="facebook"><a href="#"><i class="fa fa-google-plus-square fa-3x"></i></a></li>
                                    <li class="fb_text">
                                        <h4><a href="#">Follow us on Google +</a></h4>
                                    </li>
                                    <div class="clearfix"> </div>
                                </ul>
                            </div>
                            <div class="col-md-3">
                                <ul class="social_left">
                                    <li class="facebook"><a href="#"><i class="fa fa-linkedin-square fa-3x"></i></a></li>
                                    <li class="fb_text">
                                        <h4><a href="#">Follow us on LinkedIn</a></h4>
                                    </li>
                                    <div class="clearfix"> </div>
                                </ul>
                            </div>
                        </div>
                    </div>*@
                </div>
                <div class="container">

                    <div class="footer-lower">

                        <span class="footer-disclaimer" >Copyright &copy; @DateTime.Now.Year All rights reserved. | <a href="@Url.RouteUrl("TermsAndCondition")">Term & Conditions</a></span>
                                     

                    </div>

                </div>
            </div>


            @*@Scripts.Render("~/bundles/jquery")*@
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)


            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }



    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-67045220-2', 'auto');
        ga('send', 'pageview');

    </script>
            @*<script src="~/Scripts/bootstrap3-typeahead.js"></script>
            <script type="text/javascript">
            $(document).ready(function () {

                var countries;

                $("#Search").typeahead({

                    source: function (query, process) {
                        var songList = [];

                        // This is going to make an HTTP post request to the controller
                        return $.post('@Url.Action("GetSongs","Ajax")', { query: query }, function (data) {
                            // Loop through and push to the array
                            $.each(data, function (i, song) {
                                var item = song.Name;
                                songList.push(item);
                            });
                            // Process the details
                            process(songList);
                        });
                    }

                });


            });
            </script>*@
</body>
</html>