EGSW.Web/Areas/Admin/Controllers/GutterOrderController.cs
using EGSW.Data;
using EGSW.Data.Customers;
using EGSW.Framework;
using EGSW.Services;
using EGSW.Services.Directory;
using EGSW.Services.Orders;
using EGSW.Web.Areas.Admin.Models.Orders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EGSW.Web.Areas.Admin.Controllers
{
    public class GutterOrderController : BaseAdminController
    {
        private readonly ICustomerService _customerService;
        private readonly IWorkContext _workContext;
        private readonly IOrderService _orderService;
        private readonly IQuestionAnswerEntityData _questionAnswerEntityDataService;
        private readonly IZipCodeService _zipCodeService;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IDbContext _dbContext;


        public GutterOrderController(IWorkContext workContext, ICustomerService customerService, IOrderService orderService,
            IQuestionAnswerEntityData questionAnswerEntityDataService, IZipCodeService zipCodeService,
            IWorkflowMessageService workflowMessageService,
            IDateTimeHelper dateTimeHelper,
            IDbContext dbContext)
        {
            this._customerService = customerService;
            this._workContext = workContext;
            this._orderService = orderService;
            this._questionAnswerEntityDataService = questionAnswerEntityDataService;
            this._zipCodeService = zipCodeService;

            this._workflowMessageService = workflowMessageService;
            this._dateTimeHelper = dateTimeHelper;
            this._dbContext = dbContext;


        }


        protected virtual GutterCleanOrderModel PrepareOrderDetailsModel(GutterCleanOrder order)
        {
            if (order == null)
                throw new ArgumentNullException("order");
            var model = new GutterCleanOrderModel();
            model.Id = order.Id;
            model.OrderGuid =(Guid) order.OrderGuid;
            model.QuestionSquareFootage = order.QuestionSquareFootage;
            model.QuestionStyleOfGutter = order.QuestionStyleOfGutter;
            model.CustomerId = order.CustomerId;
            model.CustomerName = order.Customer.FirstName + " " + order.Customer.LastName;

            var r = _questionAnswerEntityDataService.StyleOfGuttersAnswer().Where(i => i.Value == order.QuestionStyleOfGutter).SingleOrDefault();
            model.QuestionStyleOfGutterStr = r.Text;

            model.QuestionYearBuilt = order.QuestionYearBuilt;

            var year = _questionAnswerEntityDataService.YearBuiltAnswer().Where(i => i.Value == order.QuestionYearBuilt.ToString()).SingleOrDefault();
            model.QuestionYearBuiltStr = year.Text;

            model.RoofMaterial = order.RoofMaterial;

            model.QuestionDeliveryTimeStr = "5 business days";
            if (order.QuestionDeliveryTime == 1)
                model.QuestionDeliveryTimeStr = "5 business days";

            if (order.QuestionDeliveryTime == 2)
                model.QuestionDeliveryTimeStr = "8 hours";

            if (order.QuestionDeliveryTime == 3)
                model.QuestionDeliveryTimeStr = "4 hours";


            model.OrderTotal = order.OrderTotal;

            model.Address = order.Address;

            model.City = order.City;
            model.State = order.State;

            model.Zipcode = order.Zipcode;
            model.AgentId = order.AgentId.HasValue ? (int)order.AgentId.Value : 0;

            model.PaymentStatusId = order.PaymentStatusId;
            model.OrderStatusId = order.OrderStatusId;
            model.CaptureTransactionId = order.CaptureTransactionId;
            model.CaptureTransactionResult = order.CaptureTransactionResult;
            //model.CreatedOnUtc = order.CreatedOnUtc;
            model.CreatedOnUtc = _dateTimeHelper.ConvertToUserTime(order.CreatedOnUtc, DateTimeKind.Utc);
            if (order.CompletionDateUtc.HasValue)
                model.CompletionDateUtc = _dateTimeHelper.ConvertToUserTime(order.CompletionDateUtc.Value, DateTimeKind.Utc); 
           

            // This button only show 'Admin User'
            model.HideSetAgentButton = _workContext.CurrentCustomer.IsAgent();
            
            // agent Mark Paid Button
            model.HideMarkPaidButton = true;

            model.IsAgentPaid = order.IsPayAgentWorker.HasValue ? order.IsPayAgentWorker.Value : false;

            if (_workContext.CurrentCustomer.IsAdmin())
                model.orderViewByAdmin = true;

            
            if (order.AgentId <= 0)
                model.HideSetWorkedCompletedButton = true;
            else
            {
                if (((OrderStatus)model.OrderStatusId).ToString() == OrderStatus.Complete.ToString())
                {
                    model.HideSetWorkedCompletedButton = true;
                    model.HideSetAgentButton = true;

                    if (!model.IsAgentPaid && !_workContext.CurrentCustomer.IsAgent())
                    {
                        model.HideMarkPaidButton = false;
                    }
                }
            }

            if (order.IsCustomerQa.HasValue)
            {
                if (order.IsCustomerQa.Value)
                {
                    model.ShowRating = true;

                    var orderSurvey=order.Surveries.FirstOrDefault();
                    if(orderSurvey!=null)
                    {
                        //model.Question1 =Convert.ToString( orderSurvey.Question1);
                        model.Question2 = Convert.ToString(orderSurvey.Question2);
                        model.Question3 = Convert.ToString(orderSurvey.Question3);
                        model.Question4 = Convert.ToString(orderSurvey.Question4);
                    }

                    // Rating detail will not show to agent.
                    if (_workContext.CurrentCustomer.IsAgent())
                    {
                        model.ShowRating = false;
                    }
                }

            }

            

            return model;
        }


        // GET: Admin/Order
        public ActionResult Index()
        {
            return View();
        }

        // GET: Agent Order List
        public ActionResult ListAllOrdersOfAgent(int Id)
        {
            var orderList = _orderService.GetOrderByAgentId(Id);

            ViewBag.orderList = orderList;
            return View();
        }


        // GET: Order
        
        [AdminRoleAuthorizeAttribute]
        public ActionResult GutterOrderStepList(string sortOrder, int? page)
        {

            int pageSize = 50;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;


            ViewBag.LastUpdatedDateUtcSortParm = String.IsNullOrEmpty(sortOrder) ? "LastUpdatedDateUtc_desc" : "";
            ViewBag.IdSortParm = sortOrder == "Id" ? "Id_desc" : "Id";
            ViewBag.IsAgentAssignSortParm = sortOrder == "IsAgentAssign" ? "IsAgentAssign_desc" : "IsAgentAssign";
            ViewBag.IsWorkedComplatedSortParm = sortOrder == "IsWorkedComplated" ? "IsWorkedComplated_desc" : "IsWorkedComplated";
            ViewBag.IsCustomerQaSortParm = sortOrder == "IsCustomerQa" ? "IsCustomerQa_desc" : "IsCustomerQa";
            ViewBag.IsPayAgentWorkerSortParm = sortOrder == "IsPayAgentWorker" ? "IsPayAgentWorker_desc" : "IsPayAgentWorker";            



            var products = _orderService.SearchOrders(sortOrder:sortOrder, pageIndex: pageIndex,pageSize: pageSize);

            return View(products);
        }


        // GET: Order
        [AdminRoleAuthorizeAttribute]
        public ActionResult List( string CustomerEmail, int? OrderStatusId, int? page)
        {
            ViewBag.CustomerEmailData = CustomerEmail;
            ViewBag.OrderStatusIdData = OrderStatusId;


            OrderStatus? orderStatus = OrderStatusId > 0 ? (OrderStatus?)(OrderStatusId) : null;

            int pageSize = 50;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            string sortOrder = "Id";
            //ViewBag.IdSortParm = sortOrder == "Id" ? "Id_desc" : "Id";
            var products = _orderService.SearchOrders(os:orderStatus, customerEmail:CustomerEmail, pageIndex: pageIndex,
            pageSize: pageSize, sortOrder: "Id_desc");

            return View(products);
        }


        // GET: Agent Order List
        public ActionResult AgentOrderList(int? page)
        {

            int pageSize = 50;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            var products = _orderService.SearchOrders(agentId:_workContext.CurrentCustomer.Id, pageIndex: pageIndex,
            pageSize: pageSize);

            return View(products);
        }

        

        public ActionResult OrderDetail(int orderId)
        {

            var order = _orderService.GetOrderById(orderId);

            if (order == null || order.Deleted)
                return new HttpUnauthorizedResult();

            if (_workContext.CurrentCustomer.IsAdmin())
            {

            }
            else if (_workContext.CurrentCustomer.IsAgent() && order.AgentId!=_workContext.CurrentCustomer.Id)
            {
                return RedirectToAction("OrderDetail");
            }

            var model = PrepareOrderDetailsModel(order);

            var customerList = _customerService.GetAllCustomers(new int[] { 4, 1 });
            if (customerList.Count > 0)
            {
                foreach (var customer in customerList)
                    model.AvailableAgents.Add(new SelectListItem() { Text = customer.FirstName + " " + customer.LastName, Value = customer.Id.ToString() });
            }
            return View(model);
        }

       [HttpPost]
       [FormValueRequired("Edit")]

EGSW.Web/Areas/Admin/Views/GutterOrder/AgentOrderList.cshtml
@model PagedList.IPagedList<GutterCleanOrder>
@using EGSW.Data
@using PagedList.Mvc;
@{
    ViewBag.Title = "My Order List";
    var _dateTimeHelper = DependencyResolver.Current.GetService<EGSW.Services.Directory.IDateTimeHelper>(); 
   
}


<h4>My Order List</h4>
<div class="form-fields table-responsive">
    <table class="table">
        <tr>
            <th>
                Order #
            </th>


            <th>
                Order Status
            </th>
            <th>
                Payment Status
            </th>
            <th>
                Order Total
            </th>
           
            <th>
                Created On
            </th>


            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @(((OrderStatus)item.OrderStatusId).ToString())
                </td>
                <td>

                    @(((PaymentStatus)item.PaymentStatusId).ToString())
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.OrderTotal)*@ @string.Format("{0:C}",item.OrderTotal)
                </td>
               
                <td>
                    @*@Html.DisplayFor(modelItem => item.CreatedOnUtc)*@
                    @_dateTimeHelper.ConvertToUserTime(item.CreatedOnUtc, DateTimeKind.Utc)
                </td>

                <td>
                    <a href="@Url.Action("OrderDetail", "GutterOrder", new { orderId = item.Id })">View</a>

                </td>
            </tr>
        }

    </table>

    <div id='Paging' style="text-align:center">
        @Html.PagedListPager(Model, page => Url.Action("AgentOrderList", new { page }))
    </div>
</div>

EGSW.Web/Areas/Admin/Views/GutterOrder/GutterOrderStepList.cshtml
@model PagedList.IPagedList<GutterCleanOrder>
@using EGSW.Data
@using PagedList.Mvc;
@{
    ViewBag.Title = "Checklist - In-Process Orders";
    var _dateTimeHelper = DependencyResolver.Current.GetService<EGSW.Services.Directory.IDateTimeHelper>();
   
}


<h4>Checklist - In-Process Orders</h4>
<div class="form-fields table-responsive">
    <table class="table">
        <tr>
            <th>
                
                @Html.ActionLink("Order #", "GutterOrderStepList", new { sortOrder = ViewBag.IdSortParm })
            </th>

            <th>
                Order Status
            </th>
            <th>
                Payment Status
            </th>
            <th>
                
                @Html.ActionLink("Review/Assign Agent", "GutterOrderStepList", new { sortOrder = ViewBag.IsAgentAssignSortParm })
            </th>
           
            <th>
                
                @Html.ActionLink("Work Complete", "GutterOrderStepList", new { sortOrder = ViewBag.IsWorkedComplatedSortParm })
            </th>

            

            <th>
                
                @Html.ActionLink("Customer QA", "GutterOrderStepList", new { sortOrder = ViewBag.IsCustomerQaSortParm })
            </th>

            <th>
                
                @Html.ActionLink("Pay Agent/Worker", "GutterOrderStepList", new { sortOrder = ViewBag.IsPayAgentWorkerSortParm })
            </th>

            <th>
                
                @Html.ActionLink("Last Modified", "GutterOrderStepList", new { sortOrder = ViewBag.LastUpdatedDateUtcSortParm })
            </th>           
           


        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Id)*@
                    <a href="@Url.Action("OrderDetail", "GutterOrder", new { orderId = item.Id })">@item.Id</a>
                </td>
                <td>
                    @(((OrderStatus)item.OrderStatusId).ToString())
                </td>
                <td>

                    @(((PaymentStatus)item.PaymentStatusId).ToString())
                </td>
                <td>
                    @item.IsAgentAssign
                </td>

                <td>
                    @item.IsWorkedComplated
                </td>

                

                <td>
                    @item.IsCustomerQa
                </td>
               
                <td>
                    @item.IsPayAgentWorker
                </td>

                <td>
                    @*@Html.DisplayFor(modelItem => item.LastUpdatedDateUtc)*@
                    @if (item.LastUpdatedDateUtc.HasValue)
                    { 
                        @_dateTimeHelper.ConvertToUserTime(item.LastUpdatedDateUtc.Value, DateTimeKind.Utc)
                    }
                </td>

                
            </tr>
        }

    </table>

    <div id='Paging' style="text-align:center">
        @Html.PagedListPager(Model, page => Url.Action("GutterOrderStepList", new { page }))
    </div>
</div>

EGSW.Web/Areas/Admin/Views/GutterOrder/List.cshtml
@model PagedList.IPagedList<GutterCleanOrder>
@using System.Web.Mvc
@using EGSW.Data
@using PagedList.Mvc;
@{
    ViewBag.Title = "Order List";

    var _dateTimeHelper = DependencyResolver.Current.GetService<EGSW.Services.Directory.IDateTimeHelper>();

    IList<SelectListItem> OrderStatusList = new List<SelectListItem>();   
    OrderStatusList.Add(new SelectListItem() { Text = "Pending", Value = "10" });
    OrderStatusList.Add(new SelectListItem() { Text = "Processing", Value = "20" });
    OrderStatusList.Add(new SelectListItem() { Text = "Complete", Value = "30" });
    OrderStatusList.Add(new SelectListItem() { Text = "Cancelled", Value = "40" });
    
   
}


<h4>Order List</h4>
@*@using (Html.BeginForm())*@
@using (Html.BeginForm("List", "GutterOrder", FormMethod.Get))
{

    <div class="form-horizontal">
        <h4>Search</h4>
        <hr />
        @*@Html.AntiForgeryToken()*@

        <div class="form-group">
            <label for="FirstName" class="control-label col-md-2">Customer Email</label>
            <div class="col-md-10">                
                @Html.TextBox("CustomerEmail", ViewBag.CustomerEmailData as string, new { @class = "form-control" }) 
            </div>
        </div>

        <div class="form-group">
            <label for="FirstName" class="control-label col-md-2">Order Status</label>
            <div class="col-md-10">
                @Html.DropDownList("OrderStatusId", OrderStatusList, "All", new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <label for="FirstName" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input type="submit" value="Find" class="btn btn-default" />
            </div>
        </div>



        <div class="form-fields table-responsive">
            <table class="table">
                <tr>
                    <th>
                        Order #
                    </th>

                    <th>
                        Email
                    </th>


                    <th>
                        Order Status
                    </th>
                    <th>
                        Payment Status
                    </th>
                    <th>
                        Order Total
                    </th>

                    <th>
                        Created On
                    </th>


                    <th></th>
                </tr>

                @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Customer.Email)
            </td>

            <td>
                @(((OrderStatus)item.OrderStatusId).ToString())
            </td>
            <td>

                @(((PaymentStatus)item.PaymentStatusId).ToString())
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.OrderTotal)*@ @string.Format("{0:C}",item.OrderTotal)
            </td>

            <td>
                @*@Html.DisplayFor(modelItem => item.CreatedOnUtc)*@
                @_dateTimeHelper.ConvertToUserTime(item.CreatedOnUtc, DateTimeKind.Utc)
            </td>

            <td>
                <a href="@Url.Action("OrderDetail", "GutterOrder", new { orderId = item.Id })">View</a>

            </td>
        </tr>
        }

            </table>

            <div id='Paging' style="text-align:center">
                @Html.PagedListPager(Model, page => Url.Action("List", new { page, CustomerEmail = ViewBag.CustomerEmailData, OrderStatusId = ViewBag.OrderStatusIdData }))
            </div>
        </div>
        </div>
        }

EGSW.Web/Areas/Admin/Views/GutterOrder/OrderDetail.cshtml
@model EGSW.Web.Areas.Admin.Models.Orders.GutterCleanOrderModel
@using EGSW.Data
@using EGSW.Data.Customers
@{
    var workContext = DependencyResolver.Current.GetService<EGSW.Data.IWorkContext>();
}


    <div>
        @if (Model.orderViewByAdmin)
        {

           @Html.ActionLink("Back to List", "List", "GutterOrder")
        }
        else
        {
            @Html.ActionLink("Back to List", "AgentOrderList", "GutterOrder")
        }
        
        
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="col-md-6">
        <div class="form-horizontal">
            <h4>Order Detail </h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)


            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DisplayFor(model => model.Id)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OrderGuid, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DisplayFor(model => model.OrderGuid)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">   
                    @if (workContext.CurrentCustomer.IsAdmin())
                    {
                        <a href="@Url.Action("EditCustomer", "Customer", new { id = Model.CustomerId })">@Model.CustomerName</a>
                    } 
                    else
                    {
                        @Model.CustomerName
                    }                
                    
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QuestionSquareFootage, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DisplayFor(model => model.QuestionSquareFootage)
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.QuestionYearBuiltStr, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">

                    @Html.DisplayFor(model => model.QuestionYearBuiltStr)
                </div>
            </div>

            <div style="border:5px solid #428bca;">

                <div class="form-group">
                    @Html.LabelFor(model => model.QuestionStyleOfGutterStr, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.QuestionStyleOfGutterStr)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RoofMaterial, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.RoofMaterial)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.QuestionDeliveryTimeStr, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.QuestionDeliveryTimeStr)
                    </div>
                </div>

                <div class="form-group">
                    @*@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <label for="Address" class="control-label col-md-4">Address to where gutters will be cleaned</label>
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.Address) 
                        @if(!string.IsNullOrWhiteSpace(Model.City))
                        {
                            <text>, </text> @Html.DisplayFor(model => model.City)

                        }
                        @if (!string.IsNullOrWhiteSpace(Model.State))
                        {
                            <text>, </text>@Html.DisplayFor(model => model.State)
                        }
                    </div>
                </div>
                @*<div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.City)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.State)
                    </div>
                </div>*@ 

                <div class="form-group">
                    @*@Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <label for="Zipcode" class="control-label col-md-4">Zip Code where gutters will be cleaned:</label>
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.Zipcode)
                    </div>
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.OrderStatusId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @(((OrderStatus)Model.OrderStatusId).ToString())
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PaymentStatusId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @(((PaymentStatus)Model.PaymentStatusId).ToString())
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OrderTotal, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @string.Format("{0:C}", Model.OrderTotal)
                </div>
            </div>

            @if (Model.orderViewByAdmin)
            { 
            <div class="form-group">
                @Html.LabelFor(model => model.AgentId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(m => m.AgentId, Model.AvailableAgents, "Select", new { @class = "form-control" })
                    <br />

                    @if (!Model.HideSetAgentButton)
                    {
                    <input type="submit" name="setagent" value="Set Agent" class="btn btn-default" />
                    }

                </div>
            </div>
            }
            

            

            <div class="form-group">
                @Html.LabelFor(model => model.CaptureTransactionId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DisplayFor(model => model.CaptureTransactionId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOnUtc, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DisplayFor(model => model.CreatedOnUtc)
                </div>
            </div>

            @if (Model.CompletionDateUtc.HasValue)
            {

                <div class="form-group">
                    @Html.LabelFor(model => model.CompletionDateUtc, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DisplayFor(model => model.CompletionDateUtc)
                    </div>
                </div>
            }
            
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">

@if (Model.orderViewByAdmin)
            {

                    <input type="submit" value="Save" class="btn btn-default" />
}

                    @if (!Model.HideSetWorkedCompletedButton)
                    {
                    <input type="submit" name="setworkcompleted" value="Set work completed" class="btn btn-default" />
                    }
                    
                    @if (!Model.HideMarkPaidButton)
                    {
                        <input type="submit" name="setmarkpaidagent" value="Set Mark Paid Agent" class="btn btn-default" />
                    }
                </div>
            </div>
        </div>

        </div>

        
        
        
        
        
        
        
    <div class="col-md-6">

        @if(Model.ShowRating)
        { 
            <div class="form-horizontal">
                <h4>Rating </h4>
                <hr />

                @*<div class="form-group">
                    @Html.LabelFor(model => model.Question1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        Overall, how satisfied are you with the Clean-My-Gutter service?
                        <br />
                        <b>
                        @Html.DisplayFor(model => model.Question1)
                        </b>
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Question2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        How would you rate the cleanliness of the Clean-My-Gutter service? 
                        <br />
                        <b> @Html.DisplayFor(model => model.Question2)</b>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Question3, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        Please indicate how quickly the work was completed from the time you ordered the service to the time the gutter service was completed? 
                        <br />
                        <b>@Html.DisplayFor(model => model.Question3)</b>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Question4, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        Did the workers who performed the Clean-My-Gutter cleaning service offer you any additional "handyman" services?
                        <br />
                        <b>@(Model.Question4=="1"?"Yes":"No")</b>
                        </div>
                </div>
                </div>
        }
        </div>
    }